### ISSUE TITLE
getBattery() spec doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/battery#16]
It's supposed to return a Promise.  In steps 1 and 2 it can "abort these steps" without returning anything...

**Comment by anssiko** [comment]
@bzbarsky, thanks for taking a look at the Battery Status API spec!

For the context, @bzbarsky is referring to the following steps in [`getBattery()`](https://w3c.github.io/battery/#dom-navigator-getbattery):

>1. If the incumbent settings object is not a secure context, then reject this Navigator object's battery promise with a "SecurityError" DOMException and abort these steps.
>
>2. If the browsing context is not a top-level browsing context, then reject this Navigator object's battery promise with a "SecurityError" DOMException and abort these steps.

... which can abort the algorithm and as a consequence we never reach:

>5. Return this Navigator object's battery promise and continue asynchronously.

This was an intentional design decision to keep compatibility with existing web content written against the older version of the API that never rejected the promise. Such a design was chosen at that time to mitigate the following privacy concerns, quoting [notes of June 30 2016 teleconference](https://lists.w3.org/Archives/Public/public-device-apis/2016Jul/0005.html):

>* BatteryManager is gated behind a promise allowing implementations to leave the promise in a pending state, for example, if no user consent is acquired. In particular, the promise never rejects, as to not allow implementations to know whether the user did not grant access or whether she just did not act on the request.

It seems it'd be reasonable to return the rejected promise in steps 1 and 2 as suggested, since after all if those assertions are true no readouts would be exposed anyways.

**Comment by bzbarsky** [comment]
It's fine if you never reject the promise.  But you need to _return_ the promise, whether it's settled or not.   Right now you have the equivalent of this C code:

    Promise* func() {
      if (someCondition) return;
    }

**Comment by anssiko** [comment]
Indeed, so the spec fix would be to return the promise in steps 1 and 2. I’ll update the spec accordingly in the coming days unless I hear other proposals. IIRC Chrome does not yet implement the respective steps so there is no impact on the implementation.

Thanks @bzbarsky!

**Comment by anssiko** [comment]
@bzbarsky PTAL #17.
